# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb18a62bd4d950ead7591cce11010f84bead8aa836d483a1d29668510b7a2489aeab5fba2b9d966b696e99045965116b922baf6ac767915a03c3890f273331a

test:
  secret_key_base: e5fc2aab849030ad60a88e08b330f15a0c2760b0a53cac44a1d1bdb891237f03e3caf0a04f9388778406476c0903c6b17815305a556bcc7c84086e18b9efe21c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
